#define IMCARBN_FORDHWTQCMDOVRLLIMRDSRFCTCALLSTS_CNT_U16       0U
#define IMCARBN_FORDHWTQCMDOVRLLIMRDSRTQREQ_CNT_U16            0U
#define IMCARBN_FORDHWTQCMDOVRLLIMRESAFCTCALLSTS_CNT_U16       0U
#define IMCARBN_FORDHWTQCMDOVRLLIMRESATQREQ_CNT_U16            0U
#define IMCARBN_FORDHWTQCMDOVRLLIMRFILDVEHSPD_CNT_U16          0U
#define IMCARBN_FORDHWTQCMDOVRLLIMRLKAFCTCALLSTS_CNT_U16       0U
#define IMCARBN_FORDHWTQCMDOVRLLIMRLKATQREQ_CNT_U16            0U
#define IMCARBN_FORDHWTQCMDOVRLLIMRVEHSPDVLD_CNT_U16           0U