/*===========================================================================*/
/* Module      = dr7f701373_irq.h                                            */
/* Version     = V1.00                                                       */
/*               extracted from device file dr7f701373.dvf                   */
/*               generated by DeFiXRH850 0.8.0.0                             */
/*===========================================================================*/
/*                                  COPYRIGHT                                */
/*===========================================================================*/
/* Copyright (c) 2015 by Renesas Electronics Europe GmbH,                    */
/*               a company of the Renesas Electronics Corporation            */
/*===========================================================================*/
/* Purpose:      Declarations of Interrupt Vector Table                      */
/*                                                                           */
/*===========================================================================*/
/*                                                                           */
/* Warranty Disclaimer                                                       */
/*                                                                           */
/* Because the Product(s) is licensed free of charge, there is no warranty   */
/* of any kind whatsoever and expressly disclaimed and excluded by Renesas,  */
/* either expressed or implied, including but not limited to those for       */
/* non-infringement of intellectual property, merchantability and/or         */
/* fitness for the particular purpose.                                       */
/* Renesas shall not have any obligation to maintain, service or provide bug */
/* fixes for the supplied Product(s) and/or the Application.                 */
/*                                                                           */
/* Each User is solely responsible for determining the appropriateness of    */
/* using the Product(s) and assumes all risks associated with its exercise   */
/* of rights under this Agreement, including, but not limited to the risks   */
/* and costs of program errors, compliance with applicable laws, damage to   */
/* or loss of data, programs or equipment, and unavailability or             */
/* interruption of operations.                                               */
/*                                                                           */
/* Limitation of Liability                                                   */
/*                                                                           */
/* In no event shall Renesas be liable to the User for any incidental,       */
/* consequential, indirect, or punitive damage (including but not limited    */
/* to lost profits) regardless of whether such liability is based on breach  */
/* of contract, tort, strict liability, breach of warranties, failure of     */
/* essential purpose or otherwise and even if advised of the possibility of  */
/* such damages. Renesas shall not be liable for any services or products    */
/* provided by third party vendors, developers or consultants identified or  */
/* referred to the User by Renesas in connection with the Product(s) and/or  */
/* the Application.                                                          */
/*                                                                           */
/*===========================================================================*/
/* Environment:                                                              */
/*              Device:         R7F701373xABG                                */
/*              IDE:            GHS Multi for V800  V6.xx or later           */
/*===========================================================================*/

#ifndef __R7F701373xABG_IRQ_H
#define __R7F701373xABG_IRQ_H

#define IRQ_TABLE_START                 0x00000200u

#define RESET_ENABLE                    0x00000001u

// #define SYSERR_ENABLE                   0x00000010u

// #define HVTRAP_ENABLE                   0x00000020u

//NEXTEER PATCH: BDO #define FETRAPEX_ENABLE                 0x00000030u

//NEXTEER PATCH: BDO  #define EITRAP0_ENABLE                  0x00000040u

//NEXTEER PATCH: BDO  #define EITRAP1_ENABLE                  0x00000050u

// #define RIEX_ENABLE                     0x00000060u

// #define UCPOP_ENABLE                    0x00000080u

// #define MIP_MDP_ENABLE                  0x00000090u

// #define PIEX_ENABLE                     0x000000A0u

//NEXTEER PATCH: BDO  #define MAEX_ENABLE                     0x000000C0u

// #define MAE_ENABLE                      0x000000C0u

// #define FENMI_ENABLE                    0x000000E0u

//NEXTEER PATCH: BDO    #define FEINT_ENABLE                    0x000000F0u

// #define EINTPRIO_0_ENABLE               0x00000100u

// #define EINTPRIO_1_ENABLE               0x00000110u

// #define EINTPRIO_2_ENABLE               0x00000120u

// #define EINTPRIO_3_ENABLE               0x00000130u

// #define EINTPRIO_4_ENABLE               0x00000140u

// #define EINTPRIO_5_ENABLE               0x00000150u

// #define EINTPRIO_6_ENABLE               0x00000160u

// #define EINTPRIO_7_ENABLE               0x00000170u

// #define EINTPRIO_8_ENABLE               0x00000180u

// #define EINTPRIO_9_ENABLE               0x00000190u

// #define EINTPRIO_10_ENABLE              0x000001A0u

// #define EINTPRIO_11_ENABLE              0x000001B0u

// #define EINTPRIO_12_ENABLE              0x000001C0u

// #define EINTPRIO_13_ENABLE              0x000001D0u

// #define EINTPRIO_14_ENABLE              0x000001E0u

// #define EINTPRIO_15_ENABLE              0x000001F0u

// #define INTECM0MI_ENABLE                (IRQ_TABLE_START + 0x00000000u)

// #define INTBN0_ENABLE                   (IRQ_TABLE_START + 0x00000010u)

// #define INTBN1_ENABLE                   (IRQ_TABLE_START + 0x00000014u)

// #define INTBN2_ENABLE                   (IRQ_TABLE_START + 0x00000018u)

// #define INTBN3_ENABLE                   (IRQ_TABLE_START + 0x0000001Cu)

// #define INTWDTA0_ENABLE                 (IRQ_TABLE_START + 0x00000020u)

// #define INTSW0_ENABLE                   (IRQ_TABLE_START + 0x00000024u)

// #define INTSW1_ENABLE                   (IRQ_TABLE_START + 0x00000028u)

// #define INTSW2_ENABLE                   (IRQ_TABLE_START + 0x0000002Cu)

// #define INTSTM02_ENABLE                 (IRQ_TABLE_START + 0x00000030u)

// #define INTSTM03_ENABLE                 (IRQ_TABLE_START + 0x00000034u)

// #define INTSTM04_ENABLE                 (IRQ_TABLE_START + 0x00000038u)

// #define INTSTM05_ENABLE                 (IRQ_TABLE_START + 0x0000003Cu)

// #define INTDMA0_ENABLE                  (IRQ_TABLE_START + 0x00000040u)

// #define INTDMA1_ENABLE                  (IRQ_TABLE_START + 0x00000044u)

// #define INTDMA2_ENABLE                  (IRQ_TABLE_START + 0x00000048u)

// #define INTDMA3_ENABLE                  (IRQ_TABLE_START + 0x0000004Cu)

// #define INTDMA4_ENABLE                  (IRQ_TABLE_START + 0x00000050u)

// #define INTDMA5_ENABLE                  (IRQ_TABLE_START + 0x00000054u)

// #define INTDMA6_ENABLE                  (IRQ_TABLE_START + 0x00000058u)

// #define INTDMA7_ENABLE                  (IRQ_TABLE_START + 0x0000005Cu)

// #define INTDMA8_ENABLE                  (IRQ_TABLE_START + 0x00000060u)

// #define INTDMA9_ENABLE                  (IRQ_TABLE_START + 0x00000064u)

// #define INTDMA10_ENABLE                 (IRQ_TABLE_START + 0x00000068u)

// #define INTDMA11_ENABLE                 (IRQ_TABLE_START + 0x0000006Cu)

// #define INTDMA12_ENABLE                 (IRQ_TABLE_START + 0x00000070u)

// #define INTDMA13_ENABLE                 (IRQ_TABLE_START + 0x00000074u)

// #define INTDMA14_ENABLE                 (IRQ_TABLE_START + 0x00000078u)

// #define INTDMA15_ENABLE                 (IRQ_TABLE_START + 0x0000007Cu)

// #define INTP0_ENABLE                    (IRQ_TABLE_START + 0x00000080u)

// #define INTP1_ENABLE                    (IRQ_TABLE_START + 0x00000084u)

// #define INTP2_ENABLE                    (IRQ_TABLE_START + 0x00000088u)

// #define INTP3_ENABLE                    (IRQ_TABLE_START + 0x0000008Cu)

// #define INTP4_ENABLE                    (IRQ_TABLE_START + 0x00000090u)

// #define INTOTS0OTE_ENABLE               (IRQ_TABLE_START + 0x00000094u)

// #define INTOTS0OTI_ENABLE               (IRQ_TABLE_START + 0x00000098u)

// #define INTOTS0OTULI_ENABLE             (IRQ_TABLE_START + 0x0000009Cu)

// #define INTFLXNTU_ENABLE                (IRQ_TABLE_START + 0x000000A0u)

// #define INTSTM00_ENABLE                 (IRQ_TABLE_START + 0x000000A4u)

// #define INTSTM01_ENABLE                 (IRQ_TABLE_START + 0x000000A8u)

// #define INTGTM0ERR_ENABLE               (IRQ_TABLE_START + 0x000000BCu)

// #define INTGTM0AEI_ENABLE               (IRQ_TABLE_START + 0x000000C0u)

// #define INTGTM0ARU0_ENABLE              (IRQ_TABLE_START + 0x000000C4u)

// #define INTGTM0ARU1_ENABLE              (IRQ_TABLE_START + 0x000000C8u)

// #define INTGTM0ARU2_ENABLE              (IRQ_TABLE_START + 0x000000CCu)

// #define INTGTM0CMP_ENABLE               (IRQ_TABLE_START + 0x000000D0u)

// #define INTGTM0TIM00_ENABLE             (IRQ_TABLE_START + 0x000000D4u)

// #define INTGTM0TIM02_ENABLE             (IRQ_TABLE_START + 0x000000D8u)

// #define INTGTM0TIM04_ENABLE             (IRQ_TABLE_START + 0x000000DCu)

// #define INTGTM0TIM06_ENABLE             (IRQ_TABLE_START + 0x000000E0u)

// #define INTGTM0TIM10_ENABLE             (IRQ_TABLE_START + 0x000000E4u)

// #define INTGTM0TIM12_ENABLE             (IRQ_TABLE_START + 0x000000E8u)

// #define INTGTM0TIM14_ENABLE             (IRQ_TABLE_START + 0x000000ECu)

// #define INTGTM0TIM16_ENABLE             (IRQ_TABLE_START + 0x000000F0u)

// #define INTGTM0MCS00_ENABLE             (IRQ_TABLE_START + 0x000000F4u)

// #define INTGTM0MCS02_ENABLE             (IRQ_TABLE_START + 0x000000F8u)

// #define INTGTM0MCS04_ENABLE             (IRQ_TABLE_START + 0x000000FCu)

// #define INTGTM0MCS06_ENABLE             (IRQ_TABLE_START + 0x00000100u)

// #define INTGTM0MCS08_ENABLE             (IRQ_TABLE_START + 0x00000104u)

// #define INTGTM0ATOM00_ENABLE            (IRQ_TABLE_START + 0x00000114u)

// #define INTGTM0ATOM02_ENABLE            (IRQ_TABLE_START + 0x00000118u)

// #define INTGTM0ATOM04_ENABLE            (IRQ_TABLE_START + 0x0000011Cu)

// #define INTGTM0ATOM06_ENABLE            (IRQ_TABLE_START + 0x00000120u)

// #define INTGTM0ATOM10_ENABLE            (IRQ_TABLE_START + 0x00000124u)

// #define INTGTM0ATOM12_ENABLE            (IRQ_TABLE_START + 0x00000128u)

// #define INTADCF0ERR_ENABLE              (IRQ_TABLE_START + 0x00000140u)

// #define INTADCF0I0_ENABLE               (IRQ_TABLE_START + 0x00000144u)

// #define INTADCF0I1_ENABLE               (IRQ_TABLE_START + 0x00000148u)

// #define INTADCF0I2_ENABLE               (IRQ_TABLE_START + 0x0000014Cu)

// #define INTADCF0I3_ENABLE               (IRQ_TABLE_START + 0x00000150u)

// #define INTADCF0I4_ENABLE               (IRQ_TABLE_START + 0x00000154u)

// #define INTCSIH0TIRE_ENABLE             (IRQ_TABLE_START + 0x00000158u)

// #define INTCSIH0TIR_ENABLE              (IRQ_TABLE_START + 0x0000015Cu)

// #define INTCSIH0TIC_ENABLE              (IRQ_TABLE_START + 0x00000160u)

// #define INTCSIH0TIJC_ENABLE             (IRQ_TABLE_START + 0x00000164u)

// #define INTCSIH1TIRE_ENABLE             (IRQ_TABLE_START + 0x00000168u)

// #define INTCSIH1TIR_ENABLE              (IRQ_TABLE_START + 0x0000016Cu)

// #define INTCSIH1TIC_ENABLE              (IRQ_TABLE_START + 0x00000170u)

// #define INTCSIH1TIJC_ENABLE             (IRQ_TABLE_START + 0x00000174u)

// #define INTCSIH2TIRE_ENABLE             (IRQ_TABLE_START + 0x00000178u)

// #define INTCSIH2TIR_ENABLE              (IRQ_TABLE_START + 0x0000017Cu)

// #define INTCSIH2TIC_ENABLE              (IRQ_TABLE_START + 0x00000180u)

// #define INTCSIH2TIJC_ENABLE             (IRQ_TABLE_START + 0x00000184u)

// #define INTCSIH3TIRE_ENABLE             (IRQ_TABLE_START + 0x00000188u)

// #define INTCSIH3TIR_ENABLE              (IRQ_TABLE_START + 0x0000018Cu)

// #define INTCSIH3TIC_ENABLE              (IRQ_TABLE_START + 0x00000190u)

// #define INTCSIH3TIJC_ENABLE             (IRQ_TABLE_START + 0x00000194u)

// #define INTRLIN30UR2_ENABLE             (IRQ_TABLE_START + 0x00000198u)

// #define INTRLIN30UR1_ENABLE             (IRQ_TABLE_START + 0x0000019Cu)

// #define INTRLIN30UR0_ENABLE             (IRQ_TABLE_START + 0x000001A0u)

// #define INTRLIN31UR2_ENABLE             (IRQ_TABLE_START + 0x000001A4u)

// #define INTRLIN31UR1_ENABLE             (IRQ_TABLE_START + 0x000001A8u)

// #define INTRLIN31UR0_ENABLE             (IRQ_TABLE_START + 0x000001ACu)

// #define INTHSUS0ERR_ENABLE              (IRQ_TABLE_START + 0x000001D0u)

// #define INTHSUS0RE_ENABLE               (IRQ_TABLE_START + 0x000001D4u)

// #define INTHSUS0TR_ENABLE               (IRQ_TABLE_START + 0x000001D8u)

// #define INTHSUS1ERR_ENABLE              (IRQ_TABLE_START + 0x000001DCu)

// #define INTHSUS1RE_ENABLE               (IRQ_TABLE_START + 0x000001E0u)

// #define INTHSUS1TR_ENABLE               (IRQ_TABLE_START + 0x000001E4u)

// #define INTP5_ENABLE                    (IRQ_TABLE_START + 0x00000200u)

// #define INTP6_ENABLE                    (IRQ_TABLE_START + 0x00000204u)

// #define INTP7_ENABLE                    (IRQ_TABLE_START + 0x00000208u)

// #define INTP9_ENABLE                    (IRQ_TABLE_START + 0x00000210u)

// #define INTP10_ENABLE                   (IRQ_TABLE_START + 0x00000214u)

// #define INTSTM06_ENABLE                 (IRQ_TABLE_START + 0x0000021Cu)

// #define INTSTM07_ENABLE                 (IRQ_TABLE_START + 0x00000220u)

// #define INTGTM0TIM01_ENABLE             (IRQ_TABLE_START + 0x00000234u)

// #define INTGTM0TIM03_ENABLE             (IRQ_TABLE_START + 0x00000238u)

// #define INTGTM0TIM05_ENABLE             (IRQ_TABLE_START + 0x0000023Cu)

// #define INTGTM0TIM07_ENABLE             (IRQ_TABLE_START + 0x00000240u)

// #define INTGTM0TIM11_ENABLE             (IRQ_TABLE_START + 0x00000244u)

// #define INTGTM0TIM13_ENABLE             (IRQ_TABLE_START + 0x00000248u)

// #define INTGTM0TIM15_ENABLE             (IRQ_TABLE_START + 0x0000024Cu)

// #define INTGTM0TIM17_ENABLE             (IRQ_TABLE_START + 0x00000250u)

// #define INTGTM0MCS01_ENABLE             (IRQ_TABLE_START + 0x00000254u)

// #define INTGTM0MCS03_ENABLE             (IRQ_TABLE_START + 0x00000258u)

// #define INTGTM0MCS05_ENABLE             (IRQ_TABLE_START + 0x0000025Cu)

// #define INTGTM0MCS07_ENABLE             (IRQ_TABLE_START + 0x00000260u)

// #define INTGTM0ATOM01_ENABLE            (IRQ_TABLE_START + 0x00000270u)

// #define INTGTM0ATOM03_ENABLE            (IRQ_TABLE_START + 0x00000274u)

// #define INTGTM0ATOM05_ENABLE            (IRQ_TABLE_START + 0x00000278u)

// #define INTGTM0ATOM07_ENABLE            (IRQ_TABLE_START + 0x0000027Cu)

// #define INTGTM0ATOM11_ENABLE            (IRQ_TABLE_START + 0x00000280u)

// #define INTGTM0ATOM13_ENABLE            (IRQ_TABLE_START + 0x00000284u)

// #define INTADCF1ERR_ENABLE              (IRQ_TABLE_START + 0x00000298u)

// #define INTADCF1I0_ENABLE               (IRQ_TABLE_START + 0x0000029Cu)

// #define INTADCF1I1_ENABLE               (IRQ_TABLE_START + 0x000002A0u)

// #define INTADCF1I2_ENABLE               (IRQ_TABLE_START + 0x000002A4u)

// #define INTADCF1I3_ENABLE               (IRQ_TABLE_START + 0x000002A8u)

// #define INTADCF1I4_ENABLE               (IRQ_TABLE_START + 0x000002ACu)

// #define INTMTTCANI0_ENABLE              (IRQ_TABLE_START + 0x000002B0u)

// #define INTMTTCANI1_ENABLE              (IRQ_TABLE_START + 0x000002B4u)

// #define INTMTTCANFE_ENABLE              (IRQ_TABLE_START + 0x000002B8u)

// #define INTMCAN0I0_ENABLE               (IRQ_TABLE_START + 0x000002BCu)

// #define INTMCAN0I1_ENABLE               (IRQ_TABLE_START + 0x000002C0u)

// #define INTMCAN0FE_ENABLE               (IRQ_TABLE_START + 0x000002C4u)

// #define INTMCAN1I0_ENABLE               (IRQ_TABLE_START + 0x000002C8u)

// #define INTMCAN1I1_ENABLE               (IRQ_TABLE_START + 0x000002CCu)

// #define INTMCAN1FE_ENABLE               (IRQ_TABLE_START + 0x000002D0u)

// #define INTETNA0_ENABLE                 (IRQ_TABLE_START + 0x000002E0u)

// #define INTFLX0LINE0_ENABLE             (IRQ_TABLE_START + 0x000002E8u)

// #define INTFLX0LINE1_ENABLE             (IRQ_TABLE_START + 0x000002ECu)

// #define INTFLX0TIM0_ENABLE              (IRQ_TABLE_START + 0x000002F0u)

// #define INTFLX0TIM1_ENABLE              (IRQ_TABLE_START + 0x000002F4u)

// #define INTFLX0TIM2_ENABLE              (IRQ_TABLE_START + 0x000002F8u)

// #define INTFLX0FDA_ENABLE               (IRQ_TABLE_START + 0x000002FCu)

// #define INTFLX0FW_ENABLE                (IRQ_TABLE_START + 0x00000300u)

// #define INTFLX0OW_ENABLE                (IRQ_TABLE_START + 0x00000304u)

// #define INTFLX0OT_ENABLE                (IRQ_TABLE_START + 0x00000308u)

// #define INTFLX0IQF_ENABLE               (IRQ_TABLE_START + 0x0000030Cu)

// #define INTFLX0IQE_ENABLE               (IRQ_TABLE_START + 0x00000310u)

// #define INTSENT0SI_ENABLE               (IRQ_TABLE_START + 0x00000340u)

// #define INTSENT0RI_ENABLE               (IRQ_TABLE_START + 0x00000344u)

// #define INTSENT1SI_ENABLE               (IRQ_TABLE_START + 0x00000348u)

// #define INTSENT1RI_ENABLE               (IRQ_TABLE_START + 0x0000034Cu)

// #define INTSENT2SI_ENABLE               (IRQ_TABLE_START + 0x00000350u)

// #define INTSENT2RI_ENABLE               (IRQ_TABLE_START + 0x00000354u)

// #define INTSENT3SI_ENABLE               (IRQ_TABLE_START + 0x00000358u)

// #define INTSENT3RI_ENABLE               (IRQ_TABLE_START + 0x0000035Cu)

// #define INTSENT4SI_ENABLE               (IRQ_TABLE_START + 0x00000360u)

// #define INTSENT4RI_ENABLE               (IRQ_TABLE_START + 0x00000364u)

// #define INTSENT5SI_ENABLE               (IRQ_TABLE_START + 0x00000368u)

// #define INTSENT5RI_ENABLE               (IRQ_TABLE_START + 0x0000036Cu)

// #define INTDTSTC0_ENABLE                (IRQ_TABLE_START + 0x00000390u)

// #define INTDTSTC1_ENABLE                (IRQ_TABLE_START + 0x00000394u)

// #define INTDTSTC2_ENABLE                (IRQ_TABLE_START + 0x00000398u)

// #define INTDTSTC3_ENABLE                (IRQ_TABLE_START + 0x0000039Cu)

// #define INTDTSCM0_ENABLE                (IRQ_TABLE_START + 0x000003A0u)

// #define INTDTSCM1_ENABLE                (IRQ_TABLE_START + 0x000003A4u)

// #define INTDTSCM2_ENABLE                (IRQ_TABLE_START + 0x000003A8u)

// #define INTDTSCM3_ENABLE                (IRQ_TABLE_START + 0x000003ACu)

// #define INTDCUDEGRADPE_ENABLE           (IRQ_TABLE_START + 0x000003B0u)

// #define INTFICUIF0CFRQPE_ENABLE         (IRQ_TABLE_START + 0x000003B4u)

// #define INTFICUIF0DFRQPE_ENABLE         (IRQ_TABLE_START + 0x000003B8u)

// #define INTFICUIF1CFRQPE_ENABLE         (IRQ_TABLE_START + 0x000003BCu)

// #define INTDNFA2WUF0_ENABLE             (IRQ_TABLE_START + 0x000003C0u)

// #define INTDNFA2WUF1_ENABLE             (IRQ_TABLE_START + 0x000003C4u)

// #define INTDNFA3WUF0_ENABLE             (IRQ_TABLE_START + 0x000003C8u)

// #define INTDNFA3WUF1_ENABLE             (IRQ_TABLE_START + 0x000003CCu)

// #define INTDNFA4WUF0_ENABLE             (IRQ_TABLE_START + 0x000003D0u)



#endif /* __R7F701373xABG_IRQ_H */
