typedef char __PST__CHAR;
typedef void __PST__VOID;
typedef signed char __PST__SINT8;
typedef signed short __PST__SINT16;
typedef signed int __PST__SINT32;
typedef signed long long __PST__SINT64;
typedef unsigned char __PST__UINT8;
typedef unsigned short __PST__UINT16;
typedef unsigned int __PST__UINT32;
typedef unsigned long long __PST__UINT64;
typedef float __PST__FLOAT32;
typedef __PST__VOID *__PST__g__11;
typedef double __PST__FLOAT64;
typedef __PST__VOID __PST__g__15(void);
typedef __PST__FLOAT32 *__PST__g__17;
typedef __PST__VOID __PST__g__16(__PST__g__17);
typedef __PST__UINT8 *__PST__g__19;
typedef __PST__VOID __PST__g__18(__PST__g__19);
typedef __PST__VOID __PST__g__20(__PST__FLOAT32);
typedef __PST__UINT8 __PST__g__21(__PST__UINT16, __PST__g__19);
typedef __PST__UINT32 *__PST__g__23;
typedef __PST__UINT8 __PST__g__22(__PST__g__23);
typedef __PST__UINT8 __PST__g__24(__PST__UINT8);
typedef __PST__UINT8 __PST__g__25(__PST__UINT16, __PST__UINT8, __PST__UINT8, __PST__UINT16);
typedef __PST__UINT8 __PST__g__26(__PST__UINT16, __PST__UINT8, __PST__UINT8, __PST__UINT16, __PST__UINT32, __PST__UINT32, __PST__UINT32);
typedef __PST__UINT8 __PST__g__27(__PST__g__19);
typedef const __PST__UINT16 __PST__g__30;
typedef __PST__g__30 __PST__g__29[16];
typedef __PST__FLOAT64 __PST__g__31(void);
typedef __PST__g__11 *__PST__g__32;
typedef volatile __PST__FLOAT64 __PST__g__33;
typedef __PST__SINT8 *__PST__g__35;
typedef volatile __PST__g__35 __PST__g__34;
typedef __PST__SINT8 __PST__g__37[3];
struct __PST__g__36
  {
    __PST__FLOAT32 OffsTrim;
    __PST__UINT8 OffsTrimPrfmdSts;
    __PST__g__37 __pst_unused_field___pstfiller;
  };
typedef __PST__UINT16 __PST__g__38[5];
typedef __PST__VOID __PST__g__39(__PST__SINT32);
typedef __PST__UINT32 __PST__g__40[32];
typedef __PST__FLOAT32 __PST__g__41(__PST__FLOAT32, __PST__FLOAT32, __PST__FLOAT32);
typedef struct __PST__g__36 *__PST__g__42;
typedef __PST__g__38 *__PST__g__43;
typedef __PST__UINT32 __PST__g__44(__PST__SINT32);
typedef __PST__UINT16 *__PST__g__45;
typedef __PST__g__30 *__PST__g__46;
typedef __PST__g__24 *__PST__g__47;
typedef __PST__g__27 *__PST__g__48;
typedef __PST__g__29 *__PST__g__49;
typedef __PST__g__22 *__PST__g__50;
typedef __PST__g__40 *__PST__g__51;
typedef __PST__g__39 *__PST__g__52;
typedef __PST__UINT8 __PST__g__53(__PST__UINT32);
typedef __PST__g__53 *__PST__g__54;
typedef __PST__UINT8 __PST__g__55(void);
typedef __PST__g__55 *__PST__g__56;
typedef __PST__UINT8 __PST__g__57(__PST__UINT16, __PST__UINT16);
typedef __PST__g__57 *__PST__g__58;
typedef __PST__g__26 *__PST__g__59;
typedef __PST__g__21 *__PST__g__60;
typedef __PST__g__41 *__PST__g__61;
typedef __PST__g__25 *__PST__g__62;
typedef __PST__g__44 *__PST__g__63;
typedef __PST__g__15 *__PST__g__64;
typedef __PST__g__16 *__PST__g__65;
typedef __PST__g__18 *__PST__g__66;
typedef __PST__g__20 *__PST__g__67;
typedef volatile __PST__SINT32 __PST__g__68;
typedef __PST__SINT8 __PST__g__74(void);
typedef volatile __PST__SINT8 __PST__g__75;
typedef volatile __PST__UINT8 __PST__g__76;
typedef __PST__SINT32 __PST__g__77(void);
typedef __PST__UINT32 __PST__g__78(void);
typedef volatile __PST__UINT32 __PST__g__79;
typedef volatile __PST__FLOAT32 __PST__g__80;
typedef volatile __PST__UINT16 __PST__g__81;
