%%-----------------------------------------------------------------------%
%% EA4 Component Data Dictionary - Created on 27-Jul-2017 15:26:35       %
%                                  Created with tool release: 3.0.0      %
%                                  Synergy file: %version: 1 %           %
%                                  Derived by: %derived_by: gz324f %          %
%%-----------------------------------------------------------------------%

CM321A = DataDict.FDD;
CM321A.Version = '1.1.x';
CM321A.LongName = 'Adcf1 Configuration and Use';
CM321A.ShoName  = 'Adcf1CfgAndUse';
CM321A.DesignASIL = 'D';
CM321A.Description = [...
  'This FDD is responsible for configuring and use of the ADC1.  This is ' ...
  'the ADC sampled at the 2mSec rate.'];



%%-------------------------------------------
%% Runnable Definitions                      
%%-------------------------------------------
Adcf1CfgAndUseInit1 = DataDict.Runnable;
Adcf1CfgAndUseInit1.Context = 'Rte';
Adcf1CfgAndUseInit1.TimeStep = 0;
Adcf1CfgAndUseInit1.Description = [...
  'Init runnable - configure registers and start SG0 conversion'];

Adcf1CfgAndUsePer1 = DataDict.Runnable;
Adcf1CfgAndUsePer1.Context = 'Rte';
Adcf1CfgAndUsePer1.TimeStep = 0.002;
Adcf1CfgAndUsePer1.Description = [...
  'Periodic runnable 1 - turn off conversion SG1, 2 & 3'];

Adcf1CfgAndUsePer2 = DataDict.Runnable;
Adcf1CfgAndUsePer2.Context = 'Rte';
Adcf1CfgAndUsePer2.TimeStep = 0.002;
Adcf1CfgAndUsePer2.Description = [...
  'Periodic runnable 2 - update start and end pointer'];

Adcf1EnaCnvn = DataDict.SrvRunnable;
Adcf1EnaCnvn.Context = 'Rte';
Adcf1EnaCnvn.Description = [...
  'Conversion enable runnable - SG1, 2 & 3'];
Adcf1EnaCnvn.Return = DataDict.CSReturn;
Adcf1EnaCnvn.Return.Type = 'None';
Adcf1EnaCnvn.Return.Min = [];
Adcf1EnaCnvn.Return.Max = [];
Adcf1EnaCnvn.Return.TestTolerance = [];


%%-------------------------------------------
%% Client Definitions                        
%%-------------------------------------------

%%-------------------------------------------
%% Input Signal Definition                   
%%-------------------------------------------
AdcDiagcEndPtrOutp = DataDict.IpSignal;
AdcDiagcEndPtrOutp.LongName = 'ADC 1 Diagnostic End Pointer Output';
AdcDiagcEndPtrOutp.Description = [...
  'Input defining Scan Group 1 end pointer for self diagnostic'];
AdcDiagcEndPtrOutp.DocUnits = 'Cnt';
AdcDiagcEndPtrOutp.EngDT = dt.u08;
AdcDiagcEndPtrOutp.EngInit = 23;
AdcDiagcEndPtrOutp.EngMin = 21;
AdcDiagcEndPtrOutp.EngMax = 23;
AdcDiagcEndPtrOutp.ReadIn = {'Adcf1CfgAndUsePer2'};
AdcDiagcEndPtrOutp.ReadType = 'Rte';


AdcDiagcStrtPtrOutp = DataDict.IpSignal;
AdcDiagcStrtPtrOutp.LongName = 'ADC 1 Diagnostic Start Pointer Output';
AdcDiagcStrtPtrOutp.Description = [...
  'Input defining Scan Group 1 start pointer for self diagnostic'];
AdcDiagcStrtPtrOutp.DocUnits = 'Cnt';
AdcDiagcStrtPtrOutp.EngDT = dt.u08;
AdcDiagcStrtPtrOutp.EngInit = 21;
AdcDiagcStrtPtrOutp.EngMin = 21;
AdcDiagcStrtPtrOutp.EngMax = 23;
AdcDiagcStrtPtrOutp.ReadIn = {'Adcf1CfgAndUsePer2'};
AdcDiagcStrtPtrOutp.ReadType = 'Rte';



%%-------------------------------------------
%% Output Signal Definition                  
%%-------------------------------------------

%%-------------------------------------------
%% Inter-Runnable Variable Definition        
%%-------------------------------------------

%%-------------------------------------------
%% Calibrations Definition                   
%%-------------------------------------------

%%-------------------------------------------
%% Imported Calibrations Definition                   
%%-------------------------------------------

%%-------------------------------------------
%% Non-Volatile Memory Definition            
%%-------------------------------------------

%%-------------------------------------------
%% Display Variable Definition               
%%-------------------------------------------

%%-------------------------------------------
%% Per-Instance Memory Definition            
%%-------------------------------------------
Adcf1DiagcEndPtr = DataDict.PIM;
Adcf1DiagcEndPtr.LongName = 'ADC 1 Diagnostic End Pointer';
Adcf1DiagcEndPtr.Description = [...
  'End pointer for Adc Diagnostic Scan Group'];
Adcf1DiagcEndPtr.DocUnits = 'Cnt';
Adcf1DiagcEndPtr.EngDT = dt.u08;
Adcf1DiagcEndPtr.EngMin = 0;
Adcf1DiagcEndPtr.EngMax = 255;
Adcf1DiagcEndPtr.InitRowCol = [1  1];


Adcf1DiagcStrtPtr = DataDict.PIM;
Adcf1DiagcStrtPtr.LongName = 'ADC 1 Diagnostic Start Pointer';
Adcf1DiagcStrtPtr.Description = [...
  'Start pointer for Adc Diagnostic Scan Group'];
Adcf1DiagcStrtPtr.DocUnits = 'Cnt';
Adcf1DiagcStrtPtr.EngDT = dt.u08;
Adcf1DiagcStrtPtr.EngMin = 0;
Adcf1DiagcStrtPtr.EngMax = 255;
Adcf1DiagcStrtPtr.InitRowCol = [1  1];



%%-------------------------------------------
%% Constant Definition                       
%%-------------------------------------------
ADCF0CFGANDUSE_ADCF0DIAGCSCANGROUPMAX_CNT_U08 = DataDict.Constant;
ADCF0CFGANDUSE_ADCF0DIAGCSCANGROUPMAX_CNT_U08.LongName = 'Diagnostic Scan Group Max';
ADCF0CFGANDUSE_ADCF0DIAGCSCANGROUPMAX_CNT_U08.Description = 'Scan Group Maximum';
ADCF0CFGANDUSE_ADCF0DIAGCSCANGROUPMAX_CNT_U08.DocUnits = 'Cnt';
ADCF0CFGANDUSE_ADCF0DIAGCSCANGROUPMAX_CNT_U08.EngDT = dt.u08;
ADCF0CFGANDUSE_ADCF0DIAGCSCANGROUPMAX_CNT_U08.EngVal = 23;
ADCF0CFGANDUSE_ADCF0DIAGCSCANGROUPMAX_CNT_U08.Define = 'Global';


ADCF0CFGANDUSE_ADCF0DIAGCSCANGROUPMIN_CNT_U08 = DataDict.Constant;
ADCF0CFGANDUSE_ADCF0DIAGCSCANGROUPMIN_CNT_U08.LongName = 'Diagnostic Scan Group Min';
ADCF0CFGANDUSE_ADCF0DIAGCSCANGROUPMIN_CNT_U08.Description = 'Scan Group Minimum';
ADCF0CFGANDUSE_ADCF0DIAGCSCANGROUPMIN_CNT_U08.DocUnits = 'Cnt';
ADCF0CFGANDUSE_ADCF0DIAGCSCANGROUPMIN_CNT_U08.EngDT = dt.u08;
ADCF0CFGANDUSE_ADCF0DIAGCSCANGROUPMIN_CNT_U08.EngVal = 21;
ADCF0CFGANDUSE_ADCF0DIAGCSCANGROUPMIN_CNT_U08.Define = 'Global';


ADCF1CFGANDUSE_ADCF1SGSWENACNVNANDDMAINTRPT_CNT_U08 = DataDict.Constant;
ADCF1CFGANDUSE_ADCF1SGSWENACNVNANDDMAINTRPT_CNT_U08.LongName = 'Scan Group Software Enable Conversion And DMA Interrupt';
ADCF1CFGANDUSE_ADCF1SGSWENACNVNANDDMAINTRPT_CNT_U08.Description = [...
  'Scan Group Enable Conversion And DMA Interrupt'];
ADCF1CFGANDUSE_ADCF1SGSWENACNVNANDDMAINTRPT_CNT_U08.DocUnits = 'Cnt';
ADCF1CFGANDUSE_ADCF1SGSWENACNVNANDDMAINTRPT_CNT_U08.EngDT = dt.u08;
ADCF1CFGANDUSE_ADCF1SGSWENACNVNANDDMAINTRPT_CNT_U08.EngVal = 17;
ADCF1CFGANDUSE_ADCF1SGSWENACNVNANDDMAINTRPT_CNT_U08.Define = 'Local';


ADCF1CFGANDUSE_ADCF1SGSWENACNVN_CNT_U08 = DataDict.Constant;
ADCF1CFGANDUSE_ADCF1SGSWENACNVN_CNT_U08.LongName = 'Scan Group Software Enable Conversion';
ADCF1CFGANDUSE_ADCF1SGSWENACNVN_CNT_U08.Description = 'Scan Group - Enable Conversion';
ADCF1CFGANDUSE_ADCF1SGSWENACNVN_CNT_U08.DocUnits = 'Cnt';
ADCF1CFGANDUSE_ADCF1SGSWENACNVN_CNT_U08.EngDT = dt.u08;
ADCF1CFGANDUSE_ADCF1SGSWENACNVN_CNT_U08.EngVal = 1;
ADCF1CFGANDUSE_ADCF1SGSWENACNVN_CNT_U08.Define = 'Local';


ADCF1CFGANDUSE_ADCF1SGVCEP2_CNT_U08 = DataDict.ConfigParam;
ADCF1CFGANDUSE_ADCF1SGVCEP2_CNT_U08.LongName = 'ADCF1SGVCEP2 Register';
ADCF1CFGANDUSE_ADCF1SGVCEP2_CNT_U08.Description = 'ADC1 Scan Group 2 end pointer';
ADCF1CFGANDUSE_ADCF1SGVCEP2_CNT_U08.IsBuildPrm = false;
ADCF1CFGANDUSE_ADCF1SGVCEP2_CNT_U08.DocUnits = 'Cnt';
ADCF1CFGANDUSE_ADCF1SGVCEP2_CNT_U08.EngDT = dt.u08;
ADCF1CFGANDUSE_ADCF1SGVCEP2_CNT_U08.EngVal = 0;
ADCF1CFGANDUSE_ADCF1SGVCEP2_CNT_U08.EngMin = 0;
ADCF1CFGANDUSE_ADCF1SGVCEP2_CNT_U08.EngMax = 63;
ADCF1CFGANDUSE_ADCF1SGVCEP2_CNT_U08.Define = 'Local';


ADCF1CFGANDUSE_ADCF1SGVCEP3_CNT_U08 = DataDict.ConfigParam;
ADCF1CFGANDUSE_ADCF1SGVCEP3_CNT_U08.LongName = 'ADCF1SGVCEP3 Register';
ADCF1CFGANDUSE_ADCF1SGVCEP3_CNT_U08.Description = 'ADC1 Scan Group 3 end pointer';
ADCF1CFGANDUSE_ADCF1SGVCEP3_CNT_U08.IsBuildPrm = false;
ADCF1CFGANDUSE_ADCF1SGVCEP3_CNT_U08.DocUnits = 'Cnt';
ADCF1CFGANDUSE_ADCF1SGVCEP3_CNT_U08.EngDT = dt.u08;
ADCF1CFGANDUSE_ADCF1SGVCEP3_CNT_U08.EngVal = 0;
ADCF1CFGANDUSE_ADCF1SGVCEP3_CNT_U08.EngMin = 0;
ADCF1CFGANDUSE_ADCF1SGVCEP3_CNT_U08.EngMax = 63;
ADCF1CFGANDUSE_ADCF1SGVCEP3_CNT_U08.Define = 'Local';


ADCF1CFGANDUSE_ADCF1SGVCSP2_CNT_U08 = DataDict.ConfigParam;
ADCF1CFGANDUSE_ADCF1SGVCSP2_CNT_U08.LongName = 'ADCF1SGVCSP2 Register';
ADCF1CFGANDUSE_ADCF1SGVCSP2_CNT_U08.Description = 'ADC1 Scan Group 2 start pointer';
ADCF1CFGANDUSE_ADCF1SGVCSP2_CNT_U08.IsBuildPrm = false;
ADCF1CFGANDUSE_ADCF1SGVCSP2_CNT_U08.DocUnits = 'Cnt';
ADCF1CFGANDUSE_ADCF1SGVCSP2_CNT_U08.EngDT = dt.u08;
ADCF1CFGANDUSE_ADCF1SGVCSP2_CNT_U08.EngVal = 0;
ADCF1CFGANDUSE_ADCF1SGVCSP2_CNT_U08.EngMin = 0;
ADCF1CFGANDUSE_ADCF1SGVCSP2_CNT_U08.EngMax = 63;
ADCF1CFGANDUSE_ADCF1SGVCSP2_CNT_U08.Define = 'Local';


ADCF1CFGANDUSE_ADCF1SGVCSP3_CNT_U08 = DataDict.ConfigParam;
ADCF1CFGANDUSE_ADCF1SGVCSP3_CNT_U08.LongName = 'ADCF1SGVCSP3 Register';
ADCF1CFGANDUSE_ADCF1SGVCSP3_CNT_U08.Description = 'ADC1 Scan Group 3 start pointer';
ADCF1CFGANDUSE_ADCF1SGVCSP3_CNT_U08.IsBuildPrm = false;
ADCF1CFGANDUSE_ADCF1SGVCSP3_CNT_U08.DocUnits = 'Cnt';
ADCF1CFGANDUSE_ADCF1SGVCSP3_CNT_U08.EngDT = dt.u08;
ADCF1CFGANDUSE_ADCF1SGVCSP3_CNT_U08.EngVal = 0;
ADCF1CFGANDUSE_ADCF1SGVCSP3_CNT_U08.EngMin = 0;
ADCF1CFGANDUSE_ADCF1SGVCSP3_CNT_U08.EngMax = 63;
ADCF1CFGANDUSE_ADCF1SGVCSP3_CNT_U08.Define = 'Local';


ADCF1CFGANDUSE_ADCF1VCR00_CNT_U32 = DataDict.ConfigParam;
ADCF1CFGANDUSE_ADCF1VCR00_CNT_U32.LongName = 'ADCF1VCR0 Register';
ADCF1CFGANDUSE_ADCF1VCR00_CNT_U32.Description = 'Value of the VCR0 Register';
ADCF1CFGANDUSE_ADCF1VCR00_CNT_U32.IsBuildPrm = false;
ADCF1CFGANDUSE_ADCF1VCR00_CNT_U32.DocUnits = 'Cnt';
ADCF1CFGANDUSE_ADCF1VCR00_CNT_U32.EngDT = dt.u32;
ADCF1CFGANDUSE_ADCF1VCR00_CNT_U32.EngVal = 0;
ADCF1CFGANDUSE_ADCF1VCR00_CNT_U32.EngMin = 0;
ADCF1CFGANDUSE_ADCF1VCR00_CNT_U32.EngMax = 262143;
ADCF1CFGANDUSE_ADCF1VCR00_CNT_U32.Define = 'Local';


ADCF1CFGANDUSE_ADCF1VCR02_CNT_U32 = DataDict.ConfigParam;
ADCF1CFGANDUSE_ADCF1VCR02_CNT_U32.LongName = 'ADCF1VCR2 Register';
ADCF1CFGANDUSE_ADCF1VCR02_CNT_U32.Description = 'Value of the VCR2 Register';
ADCF1CFGANDUSE_ADCF1VCR02_CNT_U32.IsBuildPrm = false;
ADCF1CFGANDUSE_ADCF1VCR02_CNT_U32.DocUnits = 'Cnt';
ADCF1CFGANDUSE_ADCF1VCR02_CNT_U32.EngDT = dt.u32;
ADCF1CFGANDUSE_ADCF1VCR02_CNT_U32.EngVal = 0;
ADCF1CFGANDUSE_ADCF1VCR02_CNT_U32.EngMin = 0;
ADCF1CFGANDUSE_ADCF1VCR02_CNT_U32.EngMax = 262143;
ADCF1CFGANDUSE_ADCF1VCR02_CNT_U32.Define = 'Local';


ADCF1CFGANDUSE_ADCF1VCR03_CNT_U32 = DataDict.ConfigParam;
ADCF1CFGANDUSE_ADCF1VCR03_CNT_U32.LongName = 'ADCF1VCR3 Register';
ADCF1CFGANDUSE_ADCF1VCR03_CNT_U32.Description = 'Value of the VCR3 Register';
ADCF1CFGANDUSE_ADCF1VCR03_CNT_U32.IsBuildPrm = false;
ADCF1CFGANDUSE_ADCF1VCR03_CNT_U32.DocUnits = 'Cnt';
ADCF1CFGANDUSE_ADCF1VCR03_CNT_U32.EngDT = dt.u32;
ADCF1CFGANDUSE_ADCF1VCR03_CNT_U32.EngVal = 0;
ADCF1CFGANDUSE_ADCF1VCR03_CNT_U32.EngMin = 0;
ADCF1CFGANDUSE_ADCF1VCR03_CNT_U32.EngMax = 262143;
ADCF1CFGANDUSE_ADCF1VCR03_CNT_U32.Define = 'Local';


ADCF1CFGANDUSE_ADCF1VCR04_CNT_U32 = DataDict.ConfigParam;
ADCF1CFGANDUSE_ADCF1VCR04_CNT_U32.LongName = 'ADCF1VCR4 Register';
ADCF1CFGANDUSE_ADCF1VCR04_CNT_U32.Description = 'Value of the VCR4 Register';
ADCF1CFGANDUSE_ADCF1VCR04_CNT_U32.IsBuildPrm = false;
ADCF1CFGANDUSE_ADCF1VCR04_CNT_U32.DocUnits = 'Cnt';
ADCF1CFGANDUSE_ADCF1VCR04_CNT_U32.EngDT = dt.u32;
ADCF1CFGANDUSE_ADCF1VCR04_CNT_U32.EngVal = 0;
ADCF1CFGANDUSE_ADCF1VCR04_CNT_U32.EngMin = 0;
ADCF1CFGANDUSE_ADCF1VCR04_CNT_U32.EngMax = 262143;
ADCF1CFGANDUSE_ADCF1VCR04_CNT_U32.Define = 'Local';


ADCF1CFGANDUSE_ADCF1VCR05_CNT_U32 = DataDict.ConfigParam;
ADCF1CFGANDUSE_ADCF1VCR05_CNT_U32.LongName = 'ADCF1VCR5 Register';
ADCF1CFGANDUSE_ADCF1VCR05_CNT_U32.Description = 'Value of the VCR5 Register';
ADCF1CFGANDUSE_ADCF1VCR05_CNT_U32.IsBuildPrm = false;
ADCF1CFGANDUSE_ADCF1VCR05_CNT_U32.DocUnits = 'Cnt';
ADCF1CFGANDUSE_ADCF1VCR05_CNT_U32.EngDT = dt.u32;
ADCF1CFGANDUSE_ADCF1VCR05_CNT_U32.EngVal = 0;
ADCF1CFGANDUSE_ADCF1VCR05_CNT_U32.EngMin = 0;
ADCF1CFGANDUSE_ADCF1VCR05_CNT_U32.EngMax = 262143;
ADCF1CFGANDUSE_ADCF1VCR05_CNT_U32.Define = 'Local';


ADCF1CFGANDUSE_ADCF1VCR06_CNT_U32 = DataDict.ConfigParam;
ADCF1CFGANDUSE_ADCF1VCR06_CNT_U32.LongName = 'ADCF1VCR6 Register';
ADCF1CFGANDUSE_ADCF1VCR06_CNT_U32.Description = 'Value of the VCR6 Register';
ADCF1CFGANDUSE_ADCF1VCR06_CNT_U32.IsBuildPrm = false;
ADCF1CFGANDUSE_ADCF1VCR06_CNT_U32.DocUnits = 'Cnt';
ADCF1CFGANDUSE_ADCF1VCR06_CNT_U32.EngDT = dt.u32;
ADCF1CFGANDUSE_ADCF1VCR06_CNT_U32.EngVal = 0;
ADCF1CFGANDUSE_ADCF1VCR06_CNT_U32.EngMin = 0;
ADCF1CFGANDUSE_ADCF1VCR06_CNT_U32.EngMax = 262143;
ADCF1CFGANDUSE_ADCF1VCR06_CNT_U32.Define = 'Local';


ADCF1CFGANDUSE_ADCF1VCR07_CNT_U32 = DataDict.ConfigParam;
ADCF1CFGANDUSE_ADCF1VCR07_CNT_U32.LongName = 'ADCF1VCR7 Register';
ADCF1CFGANDUSE_ADCF1VCR07_CNT_U32.Description = 'Value of the VCR7 Register';
ADCF1CFGANDUSE_ADCF1VCR07_CNT_U32.IsBuildPrm = false;
ADCF1CFGANDUSE_ADCF1VCR07_CNT_U32.DocUnits = 'Cnt';
ADCF1CFGANDUSE_ADCF1VCR07_CNT_U32.EngDT = dt.u32;
ADCF1CFGANDUSE_ADCF1VCR07_CNT_U32.EngVal = 0;
ADCF1CFGANDUSE_ADCF1VCR07_CNT_U32.EngMin = 0;
ADCF1CFGANDUSE_ADCF1VCR07_CNT_U32.EngMax = 262143;
ADCF1CFGANDUSE_ADCF1VCR07_CNT_U32.Define = 'Local';


ADCF1CFGANDUSE_ADCF1VCR08_CNT_U32 = DataDict.ConfigParam;
ADCF1CFGANDUSE_ADCF1VCR08_CNT_U32.LongName = 'ADCF1VCR8 Register';
ADCF1CFGANDUSE_ADCF1VCR08_CNT_U32.Description = 'Value of the VCR8 Register';
ADCF1CFGANDUSE_ADCF1VCR08_CNT_U32.IsBuildPrm = false;
ADCF1CFGANDUSE_ADCF1VCR08_CNT_U32.DocUnits = 'Cnt';
ADCF1CFGANDUSE_ADCF1VCR08_CNT_U32.EngDT = dt.u32;
ADCF1CFGANDUSE_ADCF1VCR08_CNT_U32.EngVal = 0;
ADCF1CFGANDUSE_ADCF1VCR08_CNT_U32.EngMin = 0;
ADCF1CFGANDUSE_ADCF1VCR08_CNT_U32.EngMax = 262143;
ADCF1CFGANDUSE_ADCF1VCR08_CNT_U32.Define = 'Local';


ADCF1CFGANDUSE_ADCF1VCR09_CNT_U32 = DataDict.ConfigParam;
ADCF1CFGANDUSE_ADCF1VCR09_CNT_U32.LongName = 'ADCF1VCR9 Register';
ADCF1CFGANDUSE_ADCF1VCR09_CNT_U32.Description = 'Value of the VCR9 Register';
ADCF1CFGANDUSE_ADCF1VCR09_CNT_U32.IsBuildPrm = false;
ADCF1CFGANDUSE_ADCF1VCR09_CNT_U32.DocUnits = 'Cnt';
ADCF1CFGANDUSE_ADCF1VCR09_CNT_U32.EngDT = dt.u32;
ADCF1CFGANDUSE_ADCF1VCR09_CNT_U32.EngVal = 0;
ADCF1CFGANDUSE_ADCF1VCR09_CNT_U32.EngMin = 0;
ADCF1CFGANDUSE_ADCF1VCR09_CNT_U32.EngMax = 262143;
ADCF1CFGANDUSE_ADCF1VCR09_CNT_U32.Define = 'Local';


ADCF1CFGANDUSE_ADCF1VCR10_CNT_U32 = DataDict.ConfigParam;
ADCF1CFGANDUSE_ADCF1VCR10_CNT_U32.LongName = 'ADCF1VCR10 Register';
ADCF1CFGANDUSE_ADCF1VCR10_CNT_U32.Description = 'Value of the VCR10 Register';
ADCF1CFGANDUSE_ADCF1VCR10_CNT_U32.IsBuildPrm = false;
ADCF1CFGANDUSE_ADCF1VCR10_CNT_U32.DocUnits = 'Cnt';
ADCF1CFGANDUSE_ADCF1VCR10_CNT_U32.EngDT = dt.u32;
ADCF1CFGANDUSE_ADCF1VCR10_CNT_U32.EngVal = 0;
ADCF1CFGANDUSE_ADCF1VCR10_CNT_U32.EngMin = 0;
ADCF1CFGANDUSE_ADCF1VCR10_CNT_U32.EngMax = 262143;
ADCF1CFGANDUSE_ADCF1VCR10_CNT_U32.Define = 'Local';


ADCF1CFGANDUSE_ADCF1VCR11_CNT_U32 = DataDict.ConfigParam;
ADCF1CFGANDUSE_ADCF1VCR11_CNT_U32.LongName = 'ADCF1VCR11 Register';
ADCF1CFGANDUSE_ADCF1VCR11_CNT_U32.Description = 'Value of the VCR11 Register';
ADCF1CFGANDUSE_ADCF1VCR11_CNT_U32.IsBuildPrm = false;
ADCF1CFGANDUSE_ADCF1VCR11_CNT_U32.DocUnits = 'Cnt';
ADCF1CFGANDUSE_ADCF1VCR11_CNT_U32.EngDT = dt.u32;
ADCF1CFGANDUSE_ADCF1VCR11_CNT_U32.EngVal = 0;
ADCF1CFGANDUSE_ADCF1VCR11_CNT_U32.EngMin = 0;
ADCF1CFGANDUSE_ADCF1VCR11_CNT_U32.EngMax = 262143;
ADCF1CFGANDUSE_ADCF1VCR11_CNT_U32.Define = 'Local';


ADCF1CFGANDUSE_ADCF1VCR12_CNT_U32 = DataDict.ConfigParam;
ADCF1CFGANDUSE_ADCF1VCR12_CNT_U32.LongName = 'ADCF1VCR12 Register';
ADCF1CFGANDUSE_ADCF1VCR12_CNT_U32.Description = 'Value of the VCR12 Register';
ADCF1CFGANDUSE_ADCF1VCR12_CNT_U32.IsBuildPrm = false;
ADCF1CFGANDUSE_ADCF1VCR12_CNT_U32.DocUnits = 'Cnt';
ADCF1CFGANDUSE_ADCF1VCR12_CNT_U32.EngDT = dt.u32;
ADCF1CFGANDUSE_ADCF1VCR12_CNT_U32.EngVal = 0;
ADCF1CFGANDUSE_ADCF1VCR12_CNT_U32.EngMin = 0;
ADCF1CFGANDUSE_ADCF1VCR12_CNT_U32.EngMax = 262143;
ADCF1CFGANDUSE_ADCF1VCR12_CNT_U32.Define = 'Local';


ADCF1CFGANDUSE_ADCF1VCR13_CNT_U32 = DataDict.ConfigParam;
ADCF1CFGANDUSE_ADCF1VCR13_CNT_U32.LongName = 'ADCF1VCR13 Register';
ADCF1CFGANDUSE_ADCF1VCR13_CNT_U32.Description = 'Value of the VCR13 Register';
ADCF1CFGANDUSE_ADCF1VCR13_CNT_U32.IsBuildPrm = false;
ADCF1CFGANDUSE_ADCF1VCR13_CNT_U32.DocUnits = 'Cnt';
ADCF1CFGANDUSE_ADCF1VCR13_CNT_U32.EngDT = dt.u32;
ADCF1CFGANDUSE_ADCF1VCR13_CNT_U32.EngVal = 0;
ADCF1CFGANDUSE_ADCF1VCR13_CNT_U32.EngMin = 0;
ADCF1CFGANDUSE_ADCF1VCR13_CNT_U32.EngMax = 262143;
ADCF1CFGANDUSE_ADCF1VCR13_CNT_U32.Define = 'Local';


ADCF1CFGANDUSE_ADCF1VCR14_CNT_U32 = DataDict.ConfigParam;
ADCF1CFGANDUSE_ADCF1VCR14_CNT_U32.LongName = 'ADCF1VCR14 Register';
ADCF1CFGANDUSE_ADCF1VCR14_CNT_U32.Description = 'Value of the VCR14 Register';
ADCF1CFGANDUSE_ADCF1VCR14_CNT_U32.IsBuildPrm = false;
ADCF1CFGANDUSE_ADCF1VCR14_CNT_U32.DocUnits = 'Cnt';
ADCF1CFGANDUSE_ADCF1VCR14_CNT_U32.EngDT = dt.u32;
ADCF1CFGANDUSE_ADCF1VCR14_CNT_U32.EngVal = 0;
ADCF1CFGANDUSE_ADCF1VCR14_CNT_U32.EngMin = 0;
ADCF1CFGANDUSE_ADCF1VCR14_CNT_U32.EngMax = 262143;
ADCF1CFGANDUSE_ADCF1VCR14_CNT_U32.Define = 'Local';


ADCF1CFGANDUSE_ADCF1VCR15_CNT_U32 = DataDict.ConfigParam;
ADCF1CFGANDUSE_ADCF1VCR15_CNT_U32.LongName = 'ADCF1VCR15 Register';
ADCF1CFGANDUSE_ADCF1VCR15_CNT_U32.Description = 'Value of the VCR15 Register';
ADCF1CFGANDUSE_ADCF1VCR15_CNT_U32.IsBuildPrm = false;
ADCF1CFGANDUSE_ADCF1VCR15_CNT_U32.DocUnits = 'Cnt';
ADCF1CFGANDUSE_ADCF1VCR15_CNT_U32.EngDT = dt.u32;
ADCF1CFGANDUSE_ADCF1VCR15_CNT_U32.EngVal = 0;
ADCF1CFGANDUSE_ADCF1VCR15_CNT_U32.EngMin = 0;
ADCF1CFGANDUSE_ADCF1VCR15_CNT_U32.EngMax = 262143;
ADCF1CFGANDUSE_ADCF1VCR15_CNT_U32.Define = 'Local';


ADCF1CFGANDUSE_ADCF1VCR16_CNT_U32 = DataDict.ConfigParam;
ADCF1CFGANDUSE_ADCF1VCR16_CNT_U32.LongName = 'ADCF1VCR16 Register';
ADCF1CFGANDUSE_ADCF1VCR16_CNT_U32.Description = 'Value of the VCR16 Register';
ADCF1CFGANDUSE_ADCF1VCR16_CNT_U32.IsBuildPrm = false;
ADCF1CFGANDUSE_ADCF1VCR16_CNT_U32.DocUnits = 'Cnt';
ADCF1CFGANDUSE_ADCF1VCR16_CNT_U32.EngDT = dt.u32;
ADCF1CFGANDUSE_ADCF1VCR16_CNT_U32.EngVal = 0;
ADCF1CFGANDUSE_ADCF1VCR16_CNT_U32.EngMin = 0;
ADCF1CFGANDUSE_ADCF1VCR16_CNT_U32.EngMax = 262143;
ADCF1CFGANDUSE_ADCF1VCR16_CNT_U32.Define = 'Local';


ADCF1CFGANDUSE_ADCF1VCR17_CNT_U32 = DataDict.ConfigParam;
ADCF1CFGANDUSE_ADCF1VCR17_CNT_U32.LongName = 'ADCF1VCR17 Register';
ADCF1CFGANDUSE_ADCF1VCR17_CNT_U32.Description = 'Value of the VCR17 Register';
ADCF1CFGANDUSE_ADCF1VCR17_CNT_U32.IsBuildPrm = false;
ADCF1CFGANDUSE_ADCF1VCR17_CNT_U32.DocUnits = 'Cnt';
ADCF1CFGANDUSE_ADCF1VCR17_CNT_U32.EngDT = dt.u32;
ADCF1CFGANDUSE_ADCF1VCR17_CNT_U32.EngVal = 0;
ADCF1CFGANDUSE_ADCF1VCR17_CNT_U32.EngMin = 0;
ADCF1CFGANDUSE_ADCF1VCR17_CNT_U32.EngMax = 262143;
ADCF1CFGANDUSE_ADCF1VCR17_CNT_U32.Define = 'Local';


ADCF1CFGANDUSE_ADCF1VCR18_CNT_U32 = DataDict.ConfigParam;
ADCF1CFGANDUSE_ADCF1VCR18_CNT_U32.LongName = 'ADCF1VCR18 Register';
ADCF1CFGANDUSE_ADCF1VCR18_CNT_U32.Description = 'Value of the VCR18 Register';
ADCF1CFGANDUSE_ADCF1VCR18_CNT_U32.IsBuildPrm = false;
ADCF1CFGANDUSE_ADCF1VCR18_CNT_U32.DocUnits = 'Cnt';
ADCF1CFGANDUSE_ADCF1VCR18_CNT_U32.EngDT = dt.u32;
ADCF1CFGANDUSE_ADCF1VCR18_CNT_U32.EngVal = 0;
ADCF1CFGANDUSE_ADCF1VCR18_CNT_U32.EngMin = 0;
ADCF1CFGANDUSE_ADCF1VCR18_CNT_U32.EngMax = 262143;
ADCF1CFGANDUSE_ADCF1VCR18_CNT_U32.Define = 'Local';


ADCF1CFGANDUSE_ADCF1VCR19_CNT_U32 = DataDict.ConfigParam;
ADCF1CFGANDUSE_ADCF1VCR19_CNT_U32.LongName = 'ADCF1VCR19 Register';
ADCF1CFGANDUSE_ADCF1VCR19_CNT_U32.Description = 'Value of the VCR19 Register';
ADCF1CFGANDUSE_ADCF1VCR19_CNT_U32.IsBuildPrm = false;
ADCF1CFGANDUSE_ADCF1VCR19_CNT_U32.DocUnits = 'Cnt';
ADCF1CFGANDUSE_ADCF1VCR19_CNT_U32.EngDT = dt.u32;
ADCF1CFGANDUSE_ADCF1VCR19_CNT_U32.EngVal = 0;
ADCF1CFGANDUSE_ADCF1VCR19_CNT_U32.EngMin = 0;
ADCF1CFGANDUSE_ADCF1VCR19_CNT_U32.EngMax = 262143;
ADCF1CFGANDUSE_ADCF1VCR19_CNT_U32.Define = 'Local';


ADCF1CFGANDUSE_ADCF1VCR1_CNT_U32 = DataDict.ConfigParam;
ADCF1CFGANDUSE_ADCF1VCR1_CNT_U32.LongName = 'ADCF1VCR1 Register';
ADCF1CFGANDUSE_ADCF1VCR1_CNT_U32.Description = 'Value of the VCR1 Register';
ADCF1CFGANDUSE_ADCF1VCR1_CNT_U32.IsBuildPrm = false;
ADCF1CFGANDUSE_ADCF1VCR1_CNT_U32.DocUnits = 'Cnt';
ADCF1CFGANDUSE_ADCF1VCR1_CNT_U32.EngDT = dt.u32;
ADCF1CFGANDUSE_ADCF1VCR1_CNT_U32.EngVal = 0;
ADCF1CFGANDUSE_ADCF1VCR1_CNT_U32.EngMin = 0;
ADCF1CFGANDUSE_ADCF1VCR1_CNT_U32.EngMax = 262143;
ADCF1CFGANDUSE_ADCF1VCR1_CNT_U32.Define = 'Local';


ADCF1CFGANDUSE_ADCF1VCR20_CNT_U32 = DataDict.ConfigParam;
ADCF1CFGANDUSE_ADCF1VCR20_CNT_U32.LongName = 'ADCF1VCR20 Register';
ADCF1CFGANDUSE_ADCF1VCR20_CNT_U32.Description = 'Value of the VCR20 Register';
ADCF1CFGANDUSE_ADCF1VCR20_CNT_U32.IsBuildPrm = false;
ADCF1CFGANDUSE_ADCF1VCR20_CNT_U32.DocUnits = 'Cnt';
ADCF1CFGANDUSE_ADCF1VCR20_CNT_U32.EngDT = dt.u32;
ADCF1CFGANDUSE_ADCF1VCR20_CNT_U32.EngVal = 0;
ADCF1CFGANDUSE_ADCF1VCR20_CNT_U32.EngMin = 0;
ADCF1CFGANDUSE_ADCF1VCR20_CNT_U32.EngMax = 262143;
ADCF1CFGANDUSE_ADCF1VCR20_CNT_U32.Define = 'Local';


ADCF1CFGANDUSE_ADCF1VCR21_CNT_U32 = DataDict.Constant;
ADCF1CFGANDUSE_ADCF1VCR21_CNT_U32.LongName = 'ADCF1VCR21 Register';
ADCF1CFGANDUSE_ADCF1VCR21_CNT_U32.Description = 'Value of the VCR21 Register';
ADCF1CFGANDUSE_ADCF1VCR21_CNT_U32.DocUnits = 'Cnt';
ADCF1CFGANDUSE_ADCF1VCR21_CNT_U32.EngDT = dt.u32;
ADCF1CFGANDUSE_ADCF1VCR21_CNT_U32.EngVal = 24584;
ADCF1CFGANDUSE_ADCF1VCR21_CNT_U32.Define = 'Local';


ADCF1CFGANDUSE_ADCF1VCR22_CNT_U32 = DataDict.Constant;
ADCF1CFGANDUSE_ADCF1VCR22_CNT_U32.LongName = 'ADCF1VCR22 Register';
ADCF1CFGANDUSE_ADCF1VCR22_CNT_U32.Description = 'Value of the VCR22 Register';
ADCF1CFGANDUSE_ADCF1VCR22_CNT_U32.DocUnits = 'Cnt';
ADCF1CFGANDUSE_ADCF1VCR22_CNT_U32.EngDT = dt.u32;
ADCF1CFGANDUSE_ADCF1VCR22_CNT_U32.EngVal = 24592;
ADCF1CFGANDUSE_ADCF1VCR22_CNT_U32.Define = 'Local';


ADCF1CFGANDUSE_ADCF1VCR23_CNT_U32 = DataDict.Constant;
ADCF1CFGANDUSE_ADCF1VCR23_CNT_U32.LongName = 'ADCF1VCR23 Register';
ADCF1CFGANDUSE_ADCF1VCR23_CNT_U32.Description = 'Value of the VCR23 Register';
ADCF1CFGANDUSE_ADCF1VCR23_CNT_U32.DocUnits = 'Cnt';
ADCF1CFGANDUSE_ADCF1VCR23_CNT_U32.EngDT = dt.u32;
ADCF1CFGANDUSE_ADCF1VCR23_CNT_U32.EngVal = 24576;
ADCF1CFGANDUSE_ADCF1VCR23_CNT_U32.Define = 'Local';



%%-------------------------------------------
%% NTC Definition                            
%%-------------------------------------------
%end of Data Dictionary
